module.exports = [{
  name: "@allnulled/lsw-tester",
  path: "src/lib/lsw-framework/lsw-tester",
  sourceType: "git",
  source: "https://github.com/allnulled/lsw-tester.git",
  version: "last"
}, {
  name: "@allnulled/lsw-importer",
  path: "src/lib/lsw-framework/lsw-importer",
  sourceType: "git",
  source: "https://github.com/allnulled/lsw-importer.git",
  version: "last"
}, {
  name: "@allnulled/lsw-logger",
  path: "src/lib/lsw-framework/lsw-logger",
  sourceType: "git",
  source: "https://github.com/allnulled/lsw-logger.git",
  version: "last"
}, {
  name: "@allnulled/lsw-database",
  path: "src/lib/lsw-framework/lsw-database",
  sourceType: "git",
  source: "https://github.com/allnulled/lsw-database.git",
  version: "last"
}, {
  name: "@allnulled/lsw-commander",
  path: "src/lib/lsw-framework/lsw-commander",
  sourceType: "git",
  source: "https://github.com/allnulled/lsw-commander.git",
  version: "last"
}, {
  name: "@allnulled/lsw-trigger",
  path: "src/lib/lsw-framework/lsw-trigger",
  sourceType: "git",
  source: "https://github.com/allnulled/lsw-trigger.git",
  version: "last"
}, {
  name: "@allnulled/lsw-store",
  path: "src/lib/lsw-framework/lsw-store",
  sourceType: "git",
  source: "https://github.com/allnulled/lsw-store.git",
  version: "last"
}, {
  name: "@allnulled/lsw-utils",
  path: "src/lib/lsw-framework/lsw-utils",
  sourceType: "git",
  source: "https://github.com/allnulled/lsw-utils.git",
  version: "last"
}]