module.exports = [{
  name: "@allnulled/lsw-tester",
  path: "src/lib/lsw-framework/src/apis/lsw-tester",
  sourceType: "git",
  source: "https://github.com/allnulled/lsw-tester.git",
  version: "last"
}, {
  name: "@allnulled/lsw-importer",
  path: "src/lib/lsw-framework/src/apis/lsw-importer",
  sourceType: "git",
  source: "https://github.com/allnulled/lsw-importer.git",
  version: "last"
}, {
  name: "@allnulled/lsw-logger",
  path: "src/lib/lsw-framework/src/apis/lsw-logger",
  sourceType: "git",
  source: "https://github.com/allnulled/lsw-logger.git",
  version: "last"
}, {
  name: "@allnulled/lsw-database",
  path: "src/lib/lsw-framework/src/apis/lsw-database",
  sourceType: "git",
  source: "https://github.com/allnulled/lsw-database.git",
  version: "last"
}, {
  name: "@allnulled/lsw-commander",
  path: "src/lib/lsw-framework/src/apis/lsw-commander",
  sourceType: "git",
  source: "https://github.com/allnulled/lsw-commander.git",
  version: "last"
}, {
  name: "@allnulled/lsw-trigger",
  path: "src/lib/lsw-framework/src/apis/lsw-trigger",
  sourceType: "git",
  source: "https://github.com/allnulled/lsw-trigger.git",
  version: "last"
}, {
  name: "@allnulled/lsw-store",
  path: "src/lib/lsw-framework/src/apis/lsw-store",
  sourceType: "git",
  source: "https://github.com/allnulled/lsw-store.git",
  version: "last"
}, {
  name: "@allnulled/lsw-utils",
  path: "src/lib/lsw-framework/src/apis/lsw-utils",
  sourceType: "git",
  source: "https://github.com/allnulled/lsw-utils.git",
  version: "last"
}, {
  name: "@allnulled/lsw-ensurer",
  path: "src/lib/lsw-framework/src/apis/lsw-ensurer",
  sourceType: "git",
  source: "https://github.com/allnulled/lsw-ensurer.git",
  version: "last"
}, {
  name: "@allnulled/lsw-timer",
  path: "src/lib/lsw-framework/src/apis/lsw-timer",
  sourceType: "git",
  source: "https://github.com/allnulled/lsw-timer.git",
  version: "last"
}]